uart.setup(0, 115200, 8, uart.PARITY_NONE, uart.STOPBITS_1, 1)
--wifi.setmode(wifi.STATION)
--wifi.sta.config("mxjk", "mxjk2015")
m = mqtt.Client("ad7cad07680c47ff80677b3c19bbe6dc", 120, "mbltest01/nodemcu01", "e61m/mza6z5HY0eD4n/sbagP6mkDZeFfmmxSh5KER0w=")
--m:lwt("/lwt", "offline", 0, 0)
--m:on("connect", function(client) print ("on connect") end)
--m:on("offline", function(client) print ("on offline") end)
m:on("message", function(client, topic, message)
    --print(topic .. ":" )
    if message ~= nil then
        --print(message)
        duty = tonumber(message)
        pwm.setduty(3, 1023 - duty)
    end
end)
m:connect("mbltest01.mqtt.iot.gz.baidubce.com", 1883, 0, 1, function(client)
--m:connect("mbltest01.mqtt.iot.gz.baidubce.com", 1884, 1, 1, function(client)
    print("connected")
    pwm.setup(3, 500, 512)
    pwm.start(3)
    m:subscribe("nodemcu01", 0, function(client)
        print("subscribe success")
        m:publish("letv1s01", "1023", 0, 0, function(client) print("sent") end)
    end)
end, function(client, reason)
    print("failed reason: "..reason)
end)
--m:subscribe("nodemcu01", 0, function(client) print("subscribe success") end)
--m:unsubscribe("nodemcu01", function(client) print("unsubscribe success") end)
--m:publish("letv1s01", "200", 0, 0, function(client) print("sent") end)
--m:close()
